name: examples-sbt-1.3

on:
  push:
    paths:
      - '.github/workflows/examples-sbt-1.3.yml'
      - 'examples/sbt-1.3/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - run: |
        cd examples/sbt-1.3
        sbt Jetty/test
