name: examples-getting-started

on:
  push:
    paths:
      - '.github/workflows/examples-getting-started.yml'
      - 'examples/getting-started/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - run: |
        cd examples/getting-started
        sbt Jetty/test
