name: examples

on:
  push:
    paths:
      - '.github/workflows/examples-lift.yml'
      - 'examples/lift/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - run: |
        cd examples/lift
        sbt Jetty/test
