name: examples-spray

on:
  push:
    paths:
      - '.github/workflows/examples-spray.yml'
      - 'examples/spray/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - run: |
        cd examples/spray
        sbt Jetty/test
