name: examples

on:
  push:
    paths:
      - 'examples/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - run: |
        for i in examples/*
        do
          pushd $i
          sbt test
          popd
        done
