name: examples

on:
  push:
    paths:
      - '.github/workflows/examples-scala-js.yml'
      - 'examples/scala-js/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - run: |
        cd examples/scala-js
        sbt fastOptJS Jetty/test
