name: examples-async

on:
  push:
    paths:
      - '.github/workflows/examples-async.yml'
      - 'examples/async/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - run: |
        cd examples/async
        sbt Jetty/test
