name: examples

on:
  push:
    paths:
      - '.github/workflows/examples-http4s.yml'
      - 'examples/http4s/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - run: |
        cd examples/http4s
        sbt Jetty/test
