name: examples-adder

on:
  push:
    paths:
      - '.github/workflows/examples-adder.yml'
      - 'examples/adder/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: |
        cd examples/adder
        sbt Jetty/test
