name: "test"

on:
  - pull_request
  - push

jobs:
  test:

    strategy:
      matrix:
        os:
          - ubuntu-24.04

    runs-on: '${{ matrix.os }}'

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: devenv

    - run: nix profile install nixpkgs#devenv

    - run: devenv test
